### PR TITLE
Update docfx.json to see if it works

### PR DESCRIPTION
**Pull request by vicancy**
https://github.com/dotnet/docfx/issues/1078

### CODE REVIEW

**Comment by richardschneider** [comment]
Good idea, but it still fails.

Could this help https://github.com/dotnet/docfx/pull/1000

**Comment by vicancy** [comment]
yes. [Microsoft Build Tools 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48159) is needed, Roslyn depends on it. 😿

**Comment by richardschneider** [comment]
I upgraded MS Build Tools with `choco` and still failed.  I'm thinking to docfx/roslyn is picking the wrong dlls.  Where are these DLLs nomally located?

I'll copy them from my machine and make appveyor use them.

Thanks for all the hard work.

**Comment by vicancy** [comment]
However your env already installed VS 2015, in theory Build Tools is no longer needed.

**Comment by richardschneider** [comment]
I changed docfx to display the loaded MSBuild modules. Notice that `Microsoft.Build.Tasks.CodeAnalysis` is missing on appveyor

On AppVeyor

- Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 
- Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 
- Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
- Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 

	 
On localhost

- Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 
- Microsoft.Build.Framework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 
- Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
- Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
- Microsoft.Build.Tasks.CodeAnalysis, Version=1.3.1.60616, Culture=neutral, PublicKeyToken=31bf3856ad364e35

**Comment by vicancy** [comment]
Looks like the failure is related to your appveyor.yml, I forked one using a simple appveyor.yml and docfx succeeds with no error. https://ci.appveyor.com/project/vicancy/net-ipfs-core https://github.com/vicancy/net-ipfs-core/blob/master/appveyor.yml

**Comment by vicancy** [comment]
Hi @richardschneider , I doubt the cause is related to AppVeyor's Visual studio version. AFAIK, only after *Visual Studio 2015 Update 3* is it compatible with assemblies in Build Tools 2015. However according to AppVeyor settings it only specifies 2015 or 2013. So it can be possible that some AppVeyor machine has the lower version than others. According to the history, https://ci.appveyor.com/project/vicancy/net-ipfs-core-cptng/history, if I remove `os: Visual Studio 2015`, in most cases, it works.....

**Comment by richardschneider** [comment]
@vicancy Thanks for all the help and the solution to the issue.

I agree, `os: ...` seems to be issue.  Very strange. I'll mention it to the appveyor team.

I'm doing some tests  and will close the issue with appropiate comments soon.

Agains thanks, Your idea of making the appyevor.yml as simple as possible was inspired.  I'm a dummy for not doing it.

cheers - Richard

**Comment by richardschneider** [comment]
After testing various changes in `appyevor.yml`, it looks like `platform: Any CPU` is the cause of all of the problems.  `os: Visual Studio 2015` is okay and I don't have to `checkout` the branch.

**Comment by vicancy** [comment]
Thanks Richard, the result is quite interesting. I will mention it in `docfx` documentation.

**Comment by richardschneider** [comment]
Good word **interesting**, as may you live in interesting times.

After looking at code in docfx and roslyn; I'm still convinced that the issue is with roslyn and msbuild.  Why doesn't roslyn have direct dependencies on msbuild?  Why does msbuild care about the platform?

**Comment by vicancy** [comment]
I can answer the first question. Why doesn't roslyn have direct dependencies on msbuild? 
Roslyn dependents on msbuild, the one installed by Build Tool 2015, it is a different version from the default msbuild 14.0.
The latter one interests me, I will investigate more when have time and let you informed.

**Comment by richardschneider** [comment]
Thank you.   I'm on makaretu at gmail dot com

**Pull request closed without merging**
